const { hasReverseCount } = require("./freddieSolution");

describe("Reverse array", () => {
  it("should solve the original version", () => {
    const testArray = ["xyz", "zxy", "zyx", "yxz", "xxz", "zzx", "xyz"];
    expect(hasReverseCount(testArray)).toEqual(5);
  });

  it("should solve the second version", () => {
    const testArray = ["lll"];
    expect(hasReverseCount(testArray)).toEqual(1);
  });

  it("should solve a 3rd version", () => {
    const testArray = [
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
      "lll",
      "kfnvushrwjfbauejgfkso",
      "kfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfksokfnvushrwjfbauejgfkso",
      "a",
      "h",
      "tee",
      "eet",
      "a",
      "nesifu",
      "there once was a man",
    ];
    expect(hasReverseCount(testArray)).toEqual(66);
  });
});
